In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

df_train = pd.read_csv('train.csv',header = 0)

In [8]:
df_train.head(100)

,datetime,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
season,,,,,,,,,,,
1,2011-01-01 00:00:00,0,0,1,9.84,14.395,81,0.0000,3,13,16
1,2011-01-01 01:00:00,0,0,1,9.02,13.635,80,0.0000,8,32,40
1,2011-01-01 02:00:00,0,0,1,9.02,13.635,80,0.0000,5,27,32
1,2011-01-01 03:00:00,0,0,1,9.84,14.395,75,0.0000,3,10,13
1,2011-01-01 04:00:00,0,0,1,9.84,14.395,75,0.0000,0,1,1
1,2011-01-01 05:00:00,0,0,2,9.84,12.880,75,6.0032,0,1,1
1,2011-01-01 06:00:00,0,0,1,9.02,13.635,80,0.0000,2,0,2
1,2011-01-01 07:00:00,0,0,1,8.20,12.880,86,0.0000,1,2,3
1,2011-01-01 08:00:00,0,0,1,9.84,14.395,75,0.0000,1,7,8
1,2011-01-01 09:00:00,0,0,1,13.12,17.425,76,0.0000,8,6,14
1,2011-01-01 10:00:00,0,0,1,15.58,19.695,76,16.9979,12,24,36
1,2011-01-01 11:00:00,0,0,1,14.76,16.665,81,19.0012,26,30,56
1,2011-01-01 12:00:00,0,0,1,17.22,21.210,77,19.0012,29,55,84
1,2011-01-01 13:00:00,0,0,2,18.86,22.725,72,19.9995,47,47,94
1,2011-01-01 14:00:00,0,0,2,18.86,22.725,72,19.0012,35,71,106
1,2011-01-01 15:00:00,0,0,2,18.04,21.970,77,19.9995,40,70,110
1,2011-01-01 16:00:00,0,0,2,17.22,21.210,82,19.9995,41,52,93
1,2011-01-01 17:00:00,0,0,2,18.04,21.970,82,19.0012,15,52,67
1,2011-01-01 18:00:00,0,0,3,17.22,21.210,88,16.9979,9,26,35
1,2011-01-01 19:00:00,0,0,3,17.22,21.210,88,16.9979,6,31,37
1,2011-01-01 20:00:00,0,0,2,16.40,20.455,87,16.9979,11,25,36
1,2011-01-01 21:00:00,0,0,2,16.40,20.455,87,12.9980,3,31,34
1,2011-01-01 22:00:00,0,0,2,16.40,20.455,94,15.0013,11,17,28
1,2011-01-01 23:00:00,0,0,2,18.86,22.725,88,19.9995,15,24,39
1,2011-01-02 00:00:00,0,0,2,18.86,22.725,88,19.9995,4,13,17
1,2011-01-02 01:00:00,0,0,2,18.04,21.970,94,16.9979,1,16,17
1,2011-01-02 02:00:00,0,0,2,17.22,21.210,100,19.0012,1,8,9
1,2011-01-02 03:00:00,0,0,2,18.86,22.725,94,12.9980,2,4,6
1,2011-01-02 04:00:00,0,0,2,18.86,22.725,94,12.9980,2,1,3
1,2011-01-02 06:00:00,0,0,3,17.22,21.210,77,19.9995,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...
1,2011-01-04 01:00:00,0,1,1,6.56,9.090,59,7.0015,0,2,2
1,2011-01-04 02:00:00,0,1,1,5.74,7.575,63,8.9981,0,1,1
1,2011-01-04 04:00:00,0,1,1,5.74,9.090,63,6.0032,0,2,2
1,2011-01-04 05:00:00,0,1,1,4.92,7.575,68,7.0015,0,4,4
1,2011-01-04 06:00:00,0,1,1,4.92,7.575,74,7.0015,0,36,36
1,2011-01-04 07:00:00,0,1,1,4.92,7.575,74,8.9981,2,92,94
1,2011-01-04 08:00:00,0,1,1,5.74,7.575,69,11.0014,2,177,179
1,2011-01-04 09:00:00,0,1,1,6.56,7.575,64,15.0013,2,98,100
1,2011-01-04 10:00:00,0,1,2,6.56,6.820,69,22.0028,5,37,42
1,2011-01-04 11:00:00,0,1,1,9.02,10.605,51,19.9995,7,50,57
1,2011-01-04 12:00:00,0,1,1,9.02,11.365,51,11.0014,12,66,78
1,2011-01-04 13:00:00,0,1,1,9.84,11.365,56,12.9980,18,79,97
1,2011-01-04 14:00:00,0,1,1,10.66,12.880,52,15.0013,9,54,63
1,2011-01-04 15:00:00,0,1,1,11.48,13.635,52,16.9979,17,48,65
1,2011-01-04 16:00:00,0,1,1,12.30,14.395,49,16.9979,15,68,83
1,2011-01-04 17:00:00,0,1,1,11.48,13.635,48,15.0013,10,202,212
1,2011-01-04 18:00:00,0,1,1,10.66,12.880,48,12.9980,3,179,182
1,2011-01-04 19:00:00,0,1,1,9.84,12.880,48,7.0015,2,110,112
1,2011-01-04 20:00:00,0,1,1,9.84,12.880,48,7.0015,1,53,54
1,2011-01-04 21:00:00,0,1,1,9.02,13.635,64,0.0000,0,48,48
1,2011-01-04 22:00:00,0,1,1,9.02,12.880,64,6.0032,1,34,35
1,2011-01-04 23:00:00,0,1,1,8.20,11.365,69,6.0032,2,9,11
1,2011-01-05 00:00:00,0,1,1,8.20,12.880,64,0.0000,0,6,6
1,2011-01-05 01:00:00,0,1,1,6.56,9.850,74,6.0032,0,6,6
1,2011-01-05 02:00:00,0,1,1,6.56,9.850,74,6.0032,0,2,2
1,2011-01-05 04:00:00,0,1,1,9.84,11.365,48,15.0013,0,2,2
1,2011-01-05 05:00:00,0,1,1,9.02,11.365,47,11.0014,0,3,3
1,2011-01-05 06:00:00,0,1,1,8.20,9.850,47,15.0013,0,33,33
1,2011-01-05 07:00:00,0,1,1,7.38,9.090,43,12.9980,1,87,88
1,2011-01-05 08:00:00,0,1,1,8.20,9.090,40,19.9995,3,192,195

In [6]:
df_train.dtypes

datetime       object
season          int64
holiday         int64
workingday      int64
weather         int64
temp          float64
atemp         float64
humidity        int64
windspeed     float64
casual          int64
registered      int64
count           int64
dtype: object

In [7]:
df_train.shape

(10886, 12)

In [8]:
df_train.count()

datetime      10886
season        10886
holiday       10886
workingday    10886
weather       10886
temp          10886
atemp         10886
humidity      10886
windspeed     10886
casual        10886
registered    10886
count         10886
dtype: int64

In [9]:
df_train['month'] = pd.DatetimeIndex(df_train.datetime).month
df_train['day'] = pd.DatetimeIndex(df_train.datetime).dayofweek
df_train['hour'] = pd.DatetimeIndex(df_train.datetime).hour

In [10]:
df_train.head(100)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count,month,day,hour
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16,1,5,0
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40,1,5,1
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32,1,5,2
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13,1,5,3
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1,1,5,4
5,2011-01-01 05:00:00,1,0,0,2,9.84,12.880,75,6.0032,0,1,1,1,5,5
6,2011-01-01 06:00:00,1,0,0,1,9.02,13.635,80,0.0000,2,0,2,1,5,6
7,2011-01-01 07:00:00,1,0,0,1,8.20,12.880,86,0.0000,1,2,3,1,5,7
8,2011-01-01 08:00:00,1,0,0,1,9.84,14.395,75,0.0000,1,7,8,1,5,8
9,2011-01-01 09:00:00,1,0,0,1,13.12,17.425,76,0.0000,8,6,14,1,5,9
10,2011-01-01 10:00:00,1,0,0,1,15.58,19.695,76,16.9979,12,24,36,1,5,10
11,2011-01-01 11:00:00,1,0,0,1,14.76,16.665,81,19.0012,26,30,56,1,5,11
12,2011-01-01 12:00:00,1,0,0,1,17.22,21.210,77,19.0012,29,55,84,1,5,12
13,2011-01-01 13:00:00,1,0,0,2,18.86,22.725,72,19.9995,47,47,94,1,5,13
14,2011-01-01 14:00:00,1,0,0,2,18.86,22.725,72,19.0012,35,71,106,1,5,14
15,2011-01-01 15:00:00,1,0,0,2,18.04,21.970,77,19.9995,40,70,110,1,5,15
16,2011-01-01 16:00:00,1,0,0,2,17.22,21.210,82,19.9995,41,52,93,1,5,16
17,2011-01-01 17:00:00,1,0,0,2,18.04,21.970,82,19.0012,15,52,67,1,5,17
18,2011-01-01 18:00:00,1,0,0,3,17.22,21.210,88,16.9979,9,26,35,1,5,18
19,2011-01-01 19:00:00,1,0,0,3,17.22,21.210,88,16.9979,6,31,37,1,5,19
20,2011-01-01 20:00:00,1,0,0,2,16.40,20.455,87,16.9979,11,25,36,1,5,20
21,2011-01-01 21:00:00,1,0,0,2,16.40,20.455,87,12.9980,3,31,34,1,5,21
22,2011-01-01 22:00:00,1,0,0,2,16.40,20.455,94,15.0013,11,17,28,1,5,22
23,2011-01-01 23:00:00,1,0,0,2,18.86,22.725,88,19.9995,15,24,39,1,5,23
24,2011-01-02 00:00:00,1,0,0,2,18.86,22.725,88,19.9995,4,13,17,1,6,0
25,2011-01-02 01:00:00,1,0,0,2,18.04,21.970,94,16.9979,1,16,17,1,6,1
26,2011-01-02 02:00:00,1,0,0,2,17.22,21.210,100,19.0012,1,8,9,1,6,2
27,2011-01-02 03:00:00,1,0,0,2,18.86,22.725,94,12.9980,2,4,6,1,6,3
28,2011-01-02 04:00:00,1,0,0,2,18.86,22.725,94,12.9980,2,1,3,1,6,4
29,2011-01-02 06:00:00,1,0,0,3,17.22,21.210,77,19.9995,0,2,2,1,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2011-01-04 01:00:00,1,0,1,1,6.56,9.090,59,7.0015,0,2,2,1,1,1
71,2011-01-04 02:00:00,1,0,1,1,5.74,7.575,63,8.9981,0,1,1,1,1,2
72,2011-01-04 04:00:00,1,0,1,1,5.74,9.090,63,6.0032,0,2,2,1,1,4
73,2011-01-04 05:00:00,1,0,1,1,4.92,7.575,68,7.0015,0,4,4,1,1,5
74,2011-01-04 06:00:00,1,0,1,1,4.92,7.575,74,7.0015,0,36,36,1,1,6
75,2011-01-04 07:00:00,1,0,1,1,4.92,7.575,74,8.9981,2,92,94,1,1,7
76,2011-01-04 08:00:00,1,0,1,1,5.74,7.575,69,11.0014,2,177,179,1,1,8
77,2011-01-04 09:00:00,1,0,1,1,6.56,7.575,64,15.0013,2,98,100,1,1,9
78,2011-01-04 10:00:00,1,0,1,2,6.56,6.820,69,22.0028,5,37,42,1,1,10
79,2011-01-04 11:00:00,1,0,1,1,9.02,10.605,51,19.9995,7,50,57,1,1,11
80,2011-01-04 12:00:00,1,0,1,1,9.02,11.365,51,11.0014,12,66,78,1,1,12
81,2011-01-04 13:00:00,1,0,1,1,9.84,11.365,56,12.9980,18,79,97,1,1,13
82,2011-01-04 14:00:00,1,0,1,1,10.66,12.880,52,15.0013,9,54,63,1,1,14
83,2011-01-04 15:00:00,1,0,1,1,11.48,13.635,52,16.9979,17,48,65,1,1,15
84,2011-01-04 16:00:00,1,0,1,1,12.30,14.395,49,16.9979,15,68,83,1,1,16
85,2011-01-04 17:00:00,1,0,1,1,11.48,13.635,48,15.0013,10,202,212,1,1,17
86,2011-01-04 18:00:00,1,0,1,1,10.66,12.880,48,12.9980,3,179,182,1,1,18
87,2011-01-04 19:00:00,1,0,1,1,9.84,12.880,48,7.0015,2,110,112,1,1,19
88,2011-01-04 20:00:00,1,0,1,1,9.84,12.880,48,7.0015,1,53,54,1,1,20
89,2011-01-04 21:00:00,1,0,1,1,9.02,13.635,64,0.0000,0,48,48,1,1,21
90,2011-01-04 22:00:00,1,0,1,1,9.02,12.880,64,6.0032,1,34,35,1,1,22
91,2011-01-04 23:00:00,1,0,1,1,8.20,11.365,69,6.0032,2,9,11,1,1,23
92,2011-01-05 00:00:00,1,0,1,1,8.20,12.880,64,0.0000,0,6,6,1,2,0
93,2011-01-05 01:00:00,1,0,1,1,6.56,9.850,74,6.0032,0,6,6,1,2,1
94,2011-01-05 02:00:00,1,0,1,1,6.56,9.850,74,6.0032,0,2,2,1,2,2
95,2011-01-05 04:00:00,1,0,1,1,9.84,11.365,48,15.0013,0,2,2,1,2,4
96,2011-01-05 05:00:00,1,0,1,1,9.02,11.365,47,11.0014,0,3,3,1,2,5
97,2011-01-05 06:00:00,1,0,1,1,8.20,9.850,47,15.0013,0,33,33,1,2,6
98,2011-01-05 07:00:00,1,0,1,1,7.38,9.090,43,12.9980,1,87,88,1,2,7
99,2011-01-05 08:00:00,1,0,1,1,8.20,9.090,40,19.9995,3,192,195,1,2,8

In [12]:
df_train = df_train.drop(['datetime','casual','registered'], axis = 1)

In [13]:
df_train.head(100)

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,count,month,day,hour
0,1,0,0,1,9.84,14.395,81,0.0000,16,1,5,0
1,1,0,0,1,9.02,13.635,80,0.0000,40,1,5,1
2,1,0,0,1,9.02,13.635,80,0.0000,32,1,5,2
3,1,0,0,1,9.84,14.395,75,0.0000,13,1,5,3
4,1,0,0,1,9.84,14.395,75,0.0000,1,1,5,4
5,1,0,0,2,9.84,12.880,75,6.0032,1,1,5,5
6,1,0,0,1,9.02,13.635,80,0.0000,2,1,5,6
7,1,0,0,1,8.20,12.880,86,0.0000,3,1,5,7
8,1,0,0,1,9.84,14.395,75,0.0000,8,1,5,8
9,1,0,0,1,13.12,17.425,76,0.0000,14,1,5,9
10,1,0,0,1,15.58,19.695,76,16.9979,36,1,5,10
11,1,0,0,1,14.76,16.665,81,19.0012,56,1,5,11
12,1,0,0,1,17.22,21.210,77,19.0012,84,1,5,12
13,1,0,0,2,18.86,22.725,72,19.9995,94,1,5,13
14,1,0,0,2,18.86,22.725,72,19.0012,106,1,5,14
15,1,0,0,2,18.04,21.970,77,19.9995,110,1,5,15
16,1,0,0,2,17.22,21.210,82,19.9995,93,1,5,16
17,1,0,0,2,18.04,21.970,82,19.0012,67,1,5,17
18,1,0,0,3,17.22,21.210,88,16.9979,35,1,5,18
19,1,0,0,3,17.22,21.210,88,16.9979,37,1,5,19
20,1,0,0,2,16.40,20.455,87,16.9979,36,1,5,20
21,1,0,0,2,16.40,20.455,87,12.9980,34,1,5,21
22,1,0,0,2,16.40,20.455,94,15.0013,28,1,5,22
23,1,0,0,2,18.86,22.725,88,19.9995,39,1,5,23
24,1,0,0,2,18.86,22.725,88,19.9995,17,1,6,0
25,1,0,0,2,18.04,21.970,94,16.9979,17,1,6,1
26,1,0,0,2,17.22,21.210,100,19.0012,9,1,6,2
27,1,0,0,2,18.86,22.725,94,12.9980,6,1,6,3
28,1,0,0,2,18.86,22.725,94,12.9980,3,1,6,4
29,1,0,0,3,17.22,21.210,77,19.9995,2,1,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...
70,1,0,1,1,6.56,9.090,59,7.0015,2,1,1,1
71,1,0,1,1,5.74,7.575,63,8.9981,1,1,1,2
72,1,0,1,1,5.74,9.090,63,6.0032,2,1,1,4
73,1,0,1,1,4.92,7.575,68,7.0015,4,1,1,5
74,1,0,1,1,4.92,7.575,74,7.0015,36,1,1,6
75,1,0,1,1,4.92,7.575,74,8.9981,94,1,1,7
76,1,0,1,1,5.74,7.575,69,11.0014,179,1,1,8
77,1,0,1,1,6.56,7.575,64,15.0013,100,1,1,9
78,1,0,1,2,6.56,6.820,69,22.0028,42,1,1,10
79,1,0,1,1,9.02,10.605,51,19.9995,57,1,1,11
80,1,0,1,1,9.02,11.365,51,11.0014,78,1,1,12
81,1,0,1,1,9.84,11.365,56,12.9980,97,1,1,13
82,1,0,1,1,10.66,12.880,52,15.0013,63,1,1,14
83,1,0,1,1,11.48,13.635,52,16.9979,65,1,1,15
84,1,0,1,1,12.30,14.395,49,16.9979,83,1,1,16
85,1,0,1,1,11.48,13.635,48,15.0013,212,1,1,17
86,1,0,1,1,10.66,12.880,48,12.9980,182,1,1,18
87,1,0,1,1,9.84,12.880,48,7.0015,112,1,1,19
88,1,0,1,1,9.84,12.880,48,7.0015,54,1,1,20
89,1,0,1,1,9.02,13.635,64,0.0000,48,1,1,21
90,1,0,1,1,9.02,12.880,64,6.0032,35,1,1,22
91,1,0,1,1,8.20,11.365,69,6.0032,11,1,1,23
92,1,0,1,1,8.20,12.880,64,0.0000,6,1,2,0
93,1,0,1,1,6.56,9.850,74,6.0032,6,1,2,1
94,1,0,1,1,6.56,9.850,74,6.0032,2,1,2,2
95,1,0,1,1,9.84,11.365,48,15.0013,2,1,2,4
96,1,0,1,1,9.02,11.365,47,11.0014,3,1,2,5
97,1,0,1,1,8.20,9.850,47,15.0013,33,1,2,6
98,1,0,1,1,7.38,9.090,43,12.9980,88,1,2,7
99,1,0,1,1,8.20,9.090,40,19.9995,195,1,2,8

In [16]:
df_train_target = df_train['count'].values
df_train_data = df_train.drop(['count'],axis = 1).values
print 'df_train_data shape is ', df_train_data.shape
print 'df_train_target shape is ', df_train_target.shape

df_train_data shape is  (10886, 11)
df_train_target shape is  (10886,)